export const DEV_VIEW_HTML = `<!doctype html>
<html lang="id">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>TukangNDeso Dev Console</title>
  <style>
    :root { --ink:#17221d; --muted:#6e7b73; --line:#dfe8e1; --paper:#f5f8f4; --card:#fff; --accent:#ec6b3d; --accent-dark:#c9502a; --green:#227a52; --yellow:#f4b942; --danger:#ba3e3e; --shadow:0 16px 40px rgba(25,52,35,.09); }
    * { box-sizing:border-box; }
    body { margin:0; color:var(--ink); background:var(--paper); font:15px/1.5 Inter, ui-sans-serif, system-ui, -apple-system, sans-serif; }
    button, input, select, textarea { font:inherit; }
    button { cursor:pointer; border:0; }
    .shell { max-width:1240px; margin:0 auto; padding:28px 20px 60px; }
    .topbar { display:flex; justify-content:space-between; align-items:flex-start; gap:18px; margin-bottom:26px; }
    .eyebrow { color:var(--accent-dark); font-size:12px; font-weight:800; letter-spacing:.14em; text-transform:uppercase; }
    h1 { margin:5px 0 7px; font-size:clamp(28px,4vw,44px); line-height:1.05; letter-spacing:-.04em; }
    h2 { margin:0 0 16px; font-size:20px; letter-spacing:-.02em; }
    h3 { margin:0 0 8px; font-size:16px; }
    p { margin:0; color:var(--muted); }
    .status { display:flex; align-items:center; gap:9px; padding:10px 14px; border:1px solid var(--line); border-radius:999px; background:#fff; color:var(--green); font-weight:700; white-space:nowrap; }
    .dot { width:9px; height:9px; border-radius:50%; background:#2eaa70; box-shadow:0 0 0 4px #dff3e7; }
    .dot.off { background:var(--danger); box-shadow:0 0 0 4px #f8dfdf; }
    .tabs { display:flex; gap:8px; overflow:auto; margin-bottom:18px; padding-bottom:2px; }
    .tab { padding:11px 16px; border:1px solid var(--line); border-radius:12px; background:#fff; color:var(--muted); font-weight:750; white-space:nowrap; }
    .tab.active { color:#fff; background:var(--ink); border-color:var(--ink); }
    .panel { display:none; }
    .panel.active { display:block; animation:rise .22s ease-out; }
    @keyframes rise { from { opacity:0; transform:translateY(5px); } to { opacity:1; transform:none; } }
    .grid { display:grid; gap:16px; grid-template-columns:repeat(12,1fr); }
    .card { grid-column:span 6; padding:20px; border:1px solid var(--line); border-radius:18px; background:var(--card); box-shadow:var(--shadow); }
    .card.wide { grid-column:span 12; }
    .card.third { grid-column:span 4; }
    .card.orange { color:#fff; border-color:#dd6337; background:linear-gradient(135deg,#f17b48,#c9552b); }
    .card.orange p { color:#ffe7dc; }
    .metric { margin-top:12px; font-size:30px; font-weight:850; letter-spacing:-.04em; }
    .form-grid { display:grid; gap:12px; grid-template-columns:repeat(2,minmax(0,1fr)); }
    label { display:grid; gap:6px; color:var(--muted); font-size:12px; font-weight:750; }
    input, select, textarea { width:100%; padding:10px 12px; border:1px solid var(--line); border-radius:10px; outline:0; color:var(--ink); background:#fbfdfb; }
    input:focus, select:focus, textarea:focus { border-color:var(--accent); box-shadow:0 0 0 3px #fce1d7; }
    textarea { min-height:80px; resize:vertical; }
    .actions { display:flex; flex-wrap:wrap; gap:9px; margin-top:14px; }
    .btn { padding:10px 14px; border-radius:10px; background:var(--ink); color:#fff; font-weight:800; }
    .btn:hover { background:#30433a; }
    .btn.primary { background:var(--accent); }
    .btn.primary:hover { background:var(--accent-dark); }
    .btn.ghost { color:var(--ink); border:1px solid var(--line); background:#fff; }
    .btn.danger { background:var(--danger); }
    .result { margin-top:14px; padding:13px; border-radius:12px; background:#f1f6f1; color:#315142; white-space:pre-wrap; word-break:break-word; }
    .result.error { color:#8e3030; background:#fff0f0; }
    .result:empty { display:none; }
    .chips { display:flex; flex-wrap:wrap; gap:8px; }
    .chip { padding:8px 11px; border:1px solid var(--line); border-radius:999px; background:#fff; font-weight:700; }
    .chip.selected { color:#fff; border-color:var(--accent); background:var(--accent); }
    .list { display:grid; gap:9px; margin-top:14px; }
    .list-item { display:flex; justify-content:space-between; align-items:center; gap:12px; padding:12px; border:1px solid var(--line); border-radius:12px; }
    .list-item strong { display:block; }
    .list-item small { color:var(--muted); }
    .price { color:var(--accent-dark); font-weight:850; white-space:nowrap; }
    .hint { margin-top:10px; font-size:12px; color:var(--muted); }
    .switch { display:flex; align-items:center; gap:8px; padding-top:22px; color:var(--muted); font-weight:700; }
    .switch input { width:auto; accent-color:var(--accent); }
    @media (max-width:760px) { .topbar { display:block; } .status { display:inline-flex; margin-top:15px; } .card, .card.third { grid-column:span 12; } .form-grid { grid-template-columns:1fr; } }
  </style>
</head>
<body>
  <main class="shell">
    <header class="topbar">
      <div><div class="eyebrow">TukangNDeso · Developer Console</div><h1>Uji produk sebelum APK jadi.</h1><p>Panel lokal untuk Mojokerto Kabupaten — bukan halaman produksi.</p></div>
      <div class="status"><span id="statusDot" class="dot"></span><span id="statusText">Checking API…</span></div>
    </header>
    <nav class="tabs" aria-label="Developer tools">
      <button class="tab active" data-tab="overview">Overview</button><button class="tab" data-tab="auth">Auth & OTP</button><button class="tab" data-tab="catalog">Katalog</button><button class="tab" data-tab="pricing">Harga</button><button class="tab" data-tab="profile">Profil & Alamat</button><button class="tab" data-tab="orders">Order</button><button class="tab" data-tab="payment">Payment QRIS</button><button class="tab" data-tab="review">Review</button><button class="tab" data-tab="worker">Worker</button><button class="tab" data-tab="matching">Matching</button><button class="tab" data-tab="admin">Admin</button>
    </nav>

    <section id="overview" class="panel active"><div class="grid">
      <article class="card orange"><div class="eyebrow">Area layanan</div><h2>Mojokerto Kabupaten</h2><p>Mulai dari Mojosari, Sooko, Puri, dan Trowulan.</p><div class="metric">QRIS ready</div></article>
      <article class="card"><div class="eyebrow">Tarif awal</div><h2>Harga transparan</h2><div class="list"><div class="list-item"><span>Per jam</span><span class="price">Rp30.000</span></div><div class="list-item"><span>Per hari</span><span class="price">Rp150.000</span></div><div class="list-item"><span>Ongkos jalan</span><span class="price">Rp1.000/km</span></div></div></article>
      <article class="card wide"><h2>Checklist pengujian cepat</h2><div class="grid"><div class="card third"><h3>01 · Auth</h3><p>Kirim OTP, verifikasi, lalu simpan token.</p></div><div class="card third"><h3>02 · Katalog</h3><p>Pilih kategori dan lihat layanan aktif.</p></div><div class="card third"><h3>03 · Estimasi</h3><p>Uji jarak 10 km dan jarak di atas 25 km.</p></div></div></article>
      <article class="card wide"><h2>Seed Data Demo</h2><p class="hint">Generate 3 pelanggan, 5 tukang (sudah aktif & online), dan 1 admin — sekali klik, tanpa isi form manual.</p><div class="actions"><button class="btn primary" id="seedDemo">Generate Demo Data</button></div><div id="seedResult" class="result"></div></article>
    </div></section>

    <section id="auth" class="panel"><div class="grid">
      <article class="card"><h2>Masuk dengan OTP</h2><div class="form-grid"><label>Nomor HP<input id="phone" value="081234567890" inputmode="numeric" /></label><label>Kode OTP<input id="otp" placeholder="Kirim OTP dulu" inputmode="numeric" /></label></div><div class="actions"><button class="btn primary" id="requestOtp">Kirim OTP</button><button class="btn" id="verifyOtp">Verifikasi</button></div><div class="hint">Mode development mengembalikan kode OTP di response untuk pengujian lokal.</div><div id="authResult" class="result"></div></article>
      <article class="card"><h2>Token Switcher & Profil</h2><p class="hint">Simpan token aktif sebagai token Pelanggan atau Tukang untuk berganti peran tanpa login ulang.</p><div class="actions"><button class="btn primary" id="saveAsCustomer">Simpan sbg Pelanggan</button><button class="btn primary" id="saveAsWorker">Simpan sbg Tukang</button></div><div class="actions" style="margin-top:8px"><button class="btn ghost" id="useCustomer">Pakai Token Pelanggan</button><button class="btn ghost" id="useWorker">Pakai Token Tukang</button></div><div id="tokenSlots" class="hint" style="margin-top:10px">Pelanggan: - | Tukang: -</div><hr style="border:0;border-top:1px solid var(--line);margin:16px 0" /><div class="form-grid"><label>Nama<input id="registerName" value="Pengguna TukangNDeso" /></label><label>Email<input id="registerEmail" type="email" placeholder="opsional@example.com" /></label></div><div class="actions"><button class="btn" id="register">Simpan profil</button><button class="btn ghost" id="clearToken">Hapus token</button></div><div id="registerResult" class="result"></div></article>
    </div></section>

    <section id="catalog" class="panel"><div class="grid"><article class="card wide"><h2>Kategori layanan</h2><div id="categories" class="chips"><span class="hint">Memuat…</span></div><div id="services" class="list"></div><div id="catalogResult" class="result"></div></article></div></section>

    <section id="pricing" class="panel"><div class="grid"><article class="card"><h2>Kalkulator harga</h2><div class="form-grid"><label>Layanan<select id="serviceId"><option value="seed-AC-cuci-ac-split">Cuci AC Split</option></select></label><label>Skema<select id="scheme"><option value="hourly">Per jam</option><option value="daily">Per hari</option></select></label><label>Durasi<input id="duration" type="number" min="1" value="3" /></label><label>Jarak (km)<input id="distance" type="number" min="0" step="0.1" value="10" /></label><label>Lantai<input id="floor" type="number" min="1" value="1" /></label><label>Jadwal<input id="scheduledAt" type="datetime-local" /></label></div><div class="form-grid"><label class="switch"><input id="urgent" type="checkbox" /> Urgent</label><label class="switch"><input id="holiday" type="checkbox" /> Hari libur nasional</label></div><div class="actions"><button class="btn primary" id="estimate">Hitung estimasi</button></div><div id="pricingResult" class="result"></div></article><article class="card"><h2>Aturan aktif</h2><div class="list"><div class="list-item"><span>Minimum order hourly</span><span class="price">2 jam</span></div><div class="list-item"><span>Radius maksimal</span><span class="price">25 km</span></div><div class="list-item"><span>Minimum ongkos</span><span class="price">Rp5.000</span></div><div class="list-item"><span>Surcharge malam</span><span class="price">+30%</span></div></div><p class="hint">Jarak pada endpoint saat ini masih stub 10 km sampai integrasi PostGIS/Maps aktif.</p></article></div></section>

    <section id="profile" class="panel"><div class="grid"><article class="card"><h2>Profil aktif</h2><div id="profileData" class="result">Belum ada token. Masuk dari tab Auth & OTP.</div><div class="actions"><button class="btn" id="loadProfile">Muat profil</button><button class="btn ghost" id="loadAddresses">Muat alamat</button></div></article><article class="card"><h2>Tambah alamat</h2><div class="form-grid"><label>Label<input id="addressLabel" value="Rumah" /></label><label>Kecamatan<input id="addressDistrict" value="Mojosari" /></label><label>Alamat lengkap<input id="addressFull" value="Jl. Mojopahit No. 1" /></label><label>Kota<input id="addressCity" value="Mojokerto" /></label><label>Latitude<input id="addressLat" type="number" step="any" value="-7.4722" /></label><label>Longitude<input id="addressLng" type="number" step="any" value="112.4336" /></label></div><label class="switch"><input id="addressDefault" type="checkbox" checked /> Jadikan alamat utama</label><div class="actions"><button class="btn primary" id="addAddress">Simpan alamat</button></div><div id="addressResult" class="result"></div></article><article class="card wide"><h2>Daftar alamat</h2><div id="addressList" class="list"></div></article></div></section>

    <section id="orders" class="panel"><div class="grid">
      <article class="card"><h2>Buat order (sebagai pelanggan)</h2><p class="hint">Gunakan token dari tab Auth & OTP milik pelanggan.</p><div class="form-grid"><label>Layanan<input id="orderServiceId" value="seed-AC-cuci-ac-split" /></label><label>Skema<select id="orderScheme"><option value="hourly">Per jam</option><option value="daily">Per hari</option></select></label><label>Durasi<input id="orderDuration" type="number" min="1" value="3" /></label><label>Alamat ID<input id="orderAddressId" value="addr-dev-1" /></label><label>Jarak (km)<input id="orderDistance" type="number" min="0" step="0.1" value="12" /></label><label>Deskripsi<input id="orderDescription" value="AC bocor di kamar utama" /></label></div><div class="actions"><button class="btn primary" id="createOrder">Buat order</button><button class="btn ghost" id="loadMyOrders">Muat order saya</button></div><div id="orderCreateResult" class="result"></div></article>
      <article class="card"><h2>Order saya (pelanggan)</h2><div id="myOrdersList" class="list"><p class="hint">Belum ada order dimuat.</p></div></article>
      <article class="card wide"><h2>Panel tukang</h2><p class="hint">Gunakan token dari tab Auth & OTP milik tukang untuk terima dan proses order.</p><div class="actions"><button class="btn" id="loadIncoming">Muat order masuk</button><button class="btn ghost" id="loadActive">Muat order aktif</button></div><h3 style="margin-top:16px">Order masuk</h3><div id="incomingList" class="list"><p class="hint">Belum ada order dimuat.</p></div><h3 style="margin-top:16px">Order aktif</h3><div id="activeList" class="list"><p class="hint">Belum ada order dimuat.</p></div><div id="orderActionResult" class="result"></div></article>
    </div></section>

    <section id="payment" class="panel"><div class="grid">
      <article class="card"><h2>Generate QRIS</h2><p class="hint">Masukkan order ID (status harus COMPLETED). Gunakan token pelanggan.</p><div class="form-grid"><label>Order ID<input id="qrisOrderId" placeholder="Paste order ID dari tab Order" /></label></div><div class="actions"><button class="btn primary" id="generateQris">Generate QRIS</button></div><div id="qrisResult" class="result"></div></article>
      <article class="card"><h2>Status Pembayaran</h2><div class="form-grid"><label>Payment ID<input id="paymentStatusId" placeholder="Dari hasil generate QRIS" /></label></div><div class="actions"><button class="btn" id="checkPaymentStatus">Cek Status</button></div><div id="paymentStatusResult" class="result"></div></article>
      <article class="card"><h2>Simulasi Bayar (Dev Only)</h2><p class="hint">Tandai pembayaran sebagai lunas tanpa gateway asli. Order akan berpindah ke status PAID.</p><div class="form-grid"><label>Payment ID<input id="simulatePaymentId" placeholder="Payment ID" /></label></div><div class="actions"><button class="btn primary" id="simulatePaid">Simulasi Lunas</button></div><div id="simulateResult" class="result"></div></article>
      <article class="card"><h2>Webhook Simulasi</h2><p class="hint">Simulasikan callback dari Midtrans/Xendit. Tanpa auth header (seperti provider asli).</p><div class="form-grid"><label>Payment ID<input id="webhookPaymentId" placeholder="Payment ID" /></label><label>Reference<input id="webhookReference" value="MIDTRANS-DEV-001" /></label></div><div class="actions"><button class="btn" id="fireWebhook">Kirim Webhook</button></div><div id="webhookResult" class="result"></div></article>
    </div></section>

    <section id="review" class="panel"><div class="grid">
      <article class="card"><h2>Beri rating & review</h2><p class="hint">Hanya bisa dilakukan setelah order berstatus PAID. Gunakan token pelanggan.</p><div class="form-grid"><label>Order ID<input id="reviewOrderId" placeholder="Paste order ID" /></label><label>Rating<select id="reviewRating"><option value="5">5 - Sangat baik</option><option value="4">4 - Baik</option><option value="3">3 - Cukup</option><option value="2">2 - Kurang</option><option value="1">1 - Buruk</option></select></label></div><label>Komentar<textarea id="reviewComment" placeholder="Ceritakan pengalaman Anda"></textarea></label><div class="actions"><button class="btn primary" id="submitReview">Kirim Review</button><button class="btn ghost" id="loadReview">Muat Review</button></div><div id="reviewResult" class="result"></div></article>
      <article class="card"><h2>Review tukang</h2><div class="form-grid"><label>Worker ID<input id="workerReviewsId" placeholder="Worker ID" /></label></div><div class="actions"><button class="btn" id="loadWorkerReviews">Muat Review Tukang</button></div><div id="workerReviewsResult" class="result"></div></article>
    </div></section>

    <section id="worker" class="panel"><div class="grid">
      <article class="card"><h2>Daftar sebagai tukang</h2><p class="hint">Gunakan token dengan role tukang (dari verifikasi OTP dengan nomor berbeda).</p><div class="form-grid"><label>Nomor KTP<input id="workerKtp" value="3216012345678901" maxlength="16" /></label><label>URL Foto KTP<input id="workerKtpUrl" value="https://cdn.tukangndeso.id/ktp/sample.jpg" /></label><label>Bio<input id="workerBio" value="Tukang AC berpengalaman 5 tahun" /></label><label>Radius kerja (km)<input id="workerRadius" type="number" value="15" min="1" max="50" /></label><label>Latitude<input id="workerLat" type="number" step="any" value="-7.4722" /></label><label>Longitude<input id="workerLng" type="number" step="any" value="112.4336" /></label></div><label>Keahlian (koma dipisah)<input id="workerSkills" value="AC,LST" /></label><div class="actions"><button class="btn primary" id="registerWorker">Daftar Tukang</button><button class="btn ghost" id="loadWorkerProfile">Muat Profil</button></div><div id="workerProfileResult" class="result"></div></article>
      <article class="card"><h2>Verifikasi & Ketersediaan</h2><p class="hint">Verifikasi manual (dev-only) lalu toggle status online.</p><div class="form-grid"><label>Worker User ID<input id="verifyWorkerId" placeholder="Isi dari profil tukang" /></label></div><div class="actions"><button class="btn" id="verifyWorker">Verifikasi Tukang</button></div><hr style="border:0;border-top:1px solid var(--line);margin:16px 0" /><div class="actions"><button class="btn primary" id="goOnline">Online</button><button class="btn ghost" id="goOffline">Offline</button></div><div id="availabilityResult" class="result"></div></article>
      <article class="card wide"><h2>Wallet Tukang</h2><div class="actions"><button class="btn" id="loadWallet">Muat Wallet</button></div><div id="walletData" class="result">Belum dimuat.</div><hr style="border:0;border-top:1px solid var(--line);margin:16px 0" /><h3>Penarikan saldo</h3><div class="form-grid"><label>Jumlah<input id="withdrawAmount" type="number" min="10000" value="50000" /></label><label>Bank<input id="withdrawBank" value="BCA" /></label><label>No. Rekening<input id="withdrawAccount" value="1234567890" /></label></div><div class="actions"><button class="btn primary" id="submitWithdraw">Ajukan Penarikan</button></div><div id="withdrawResult" class="result"></div></article>
    </div></section>

    <section id="matching" class="panel"><div class="grid">
      <article class="card"><h2>Cari kandidat tukang</h2><p class="hint">Cari tukang yang cocok untuk order tertentu berdasarkan kategori, jarak, dan ketersediaan.</p><div class="form-grid"><label>Order ID<input id="matchOrderId" placeholder="Paste order ID" /></label></div><div class="actions"><button class="btn" id="findCandidates">Cari Kandidat</button><button class="btn primary" id="assignBest">Assign Otomatis</button></div><div id="matchingResult" class="result"></div></article>
      <article class="card"><h2>Assign manual</h2><p class="hint">Pilih tukang tertentu dari daftar kandidat.</p><div class="form-grid"><label>Order ID<input id="assignOrderId" placeholder="Order ID" /></label><label>Worker ID<input id="assignWorkerId" placeholder="Worker user ID" /></label></div><div class="actions"><button class="btn primary" id="assignSpecific">Assign Tukang</button></div><div id="assignResult" class="result"></div></article>
    </div></section>

    <section id="admin" class="panel"><div class="grid">
      <article class="card wide"><h2>Report Summary</h2><p class="hint">Butuh token dengan role admin. Isi phone di tab Auth &amp; OTP dengan nomor admin, lalu simpan token aktif dulu.</p><div class="actions"><button class="btn primary" id="loadReport">Muat Report</button></div><div id="reportResult" class="result">Belum dimuat.</div></article>
      <article class="card"><h2>Tukang menunggu verifikasi</h2><div class="actions"><button class="btn" id="loadPendingWorkers">Muat Pending</button></div><div id="pendingWorkersList" class="list"></div><div id="pendingWorkersResult" class="result"></div></article>
      <article class="card"><h2>Kelola tukang</h2><div class="form-grid"><label>Worker User ID<input id="adminWorkerId" placeholder="Worker user ID" /></label></div><div class="actions"><button class="btn primary" id="adminVerify">Verify</button><button class="btn" id="adminSuspend">Suspend</button><button class="btn ghost" id="adminReactivate">Reactivate</button></div><div id="adminWorkerResult" class="result"></div></article>
      <article class="card wide"><h2>Force transisi order</h2><p class="hint">Bypass state machine untuk kasus khusus (misal timeout, dispute manual).</p><div class="form-grid"><label>Order ID<input id="forceOrderId" placeholder="Order ID" /></label><label>Target status<select id="forceTargetStatus"><option value="EXPIRED">EXPIRED</option><option value="CANCELLED_BY_CUSTOMER">CANCELLED_BY_CUSTOMER</option><option value="CANCELLED_BY_WORKER">CANCELLED_BY_WORKER</option><option value="DISPUTED">DISPUTED</option><option value="PAID">PAID</option></select></label></div><label>Catatan admin<input id="forceNote" placeholder="Alasan force transisi" /></label><div class="actions"><button class="btn primary" id="forceTransition">Force Transisi</button></div><div id="forceResult" class="result"></div></article>
    </div></section>
  </main>
<script>
(function () {
  var token = localStorage.getItem('tukangndeso_token') || '';
  var customerToken = localStorage.getItem('tukangndeso_customer_token') || '';
  var workerToken = localStorage.getItem('tukangndeso_worker_token') || '';
  var $ = function (id) { return document.getElementById(id); };
  var json = function (response) { return response.json().then(function (body) { if (!response.ok) throw new Error((body.error && body.error.message) || 'Request gagal'); return body; }); };
  var show = function (id, value, error) { var el = $(id); el.textContent = typeof value === 'string' ? value : JSON.stringify(value, null, 2); el.className = error ? 'result error' : 'result'; };
  var request = function (path, options) { options = options || {}; options.headers = Object.assign({ 'Content-Type': 'application/json' }, options.headers || {}); if (token) options.headers.Authorization = 'Bearer ' + token; return fetch(path, options).then(json); };
  var escapeHtml = function (value) { return String(value).replace(/[&<>\"']/g, function (char) { return ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '\"':'&quot;', "'":'&#039;' })[char]; }); };
  var updateSlotDisplay = function () { $('tokenSlots').textContent = 'Pelanggan: ' + (customerToken ? customerToken.slice(0, 20) + '…' : '—') + ' | Tukang: ' + (workerToken ? workerToken.slice(0, 20) + '…' : '—') + ' | Aktif: ' + (token ? token.slice(0, 20) + '…' : '—'); };
  updateSlotDisplay();

  document.querySelectorAll('.tab').forEach(function (button) { button.addEventListener('click', function () { document.querySelectorAll('.tab').forEach(function (item) { item.classList.remove('active'); }); document.querySelectorAll('.panel').forEach(function (item) { item.classList.remove('active'); }); button.classList.add('active'); $(button.dataset.tab).classList.add('active'); }); });
  fetch('/health').then(json).then(function (body) { $('statusText').textContent = body.data.status === 'ok' ? 'API online' : 'API warning'; }).catch(function () { $('statusDot').classList.add('off'); $('statusText').textContent = 'API offline'; });

  $('requestOtp').addEventListener('click', function () { request('/v1/auth/otp/request', { method:'POST', body:JSON.stringify({ phone:$('phone').value }) }).then(function (body) { if (body.data.dev_otp_code) $('otp').value = body.data.dev_otp_code; show('authResult', body.data); }).catch(function (error) { show('authResult', error.message, true); }); });
  $('verifyOtp').addEventListener('click', function () { request('/v1/auth/otp/verify', { method:'POST', body:JSON.stringify({ phone:$('phone').value, code:$('otp').value }) }).then(function (body) { token = body.data.token; localStorage.setItem('tukangndeso_token', token); updateSlotDisplay(); show('authResult', body.data); }).catch(function (error) { show('authResult', error.message, true); }); });
  $('register').addEventListener('click', function () { request('/v1/auth/register', { method:'POST', body:JSON.stringify({ name:$('registerName').value, email:$('registerEmail').value || undefined }) }).then(function (body) { show('registerResult', body.data); }).catch(function (error) { show('registerResult', error.message, true); }); });
  $('clearToken').addEventListener('click', function () { token = ''; localStorage.removeItem('tukangndeso_token'); updateSlotDisplay(); show('registerResult', 'Token dihapus dari browser.'); });
  $('saveAsCustomer').addEventListener('click', function () { customerToken = token; localStorage.setItem('tukangndeso_customer_token', token); updateSlotDisplay(); show('authResult', 'Token aktif disimpan sebagai Pelanggan.'); });
  $('saveAsWorker').addEventListener('click', function () { workerToken = token; localStorage.setItem('tukangndeso_worker_token', token); updateSlotDisplay(); show('authResult', 'Token aktif disimpan sebagai Tukang.'); });
  $('useCustomer').addEventListener('click', function () { if (!customerToken) { show('authResult', 'Belum ada token pelanggan tersimpan.', true); return; } token = customerToken; localStorage.setItem('tukangndeso_token', token); updateSlotDisplay(); show('authResult', 'Switched ke token Pelanggan.'); });
  $('useWorker').addEventListener('click', function () { if (!workerToken) { show('authResult', 'Belum ada token tukang tersimpan.', true); return; } token = workerToken; localStorage.setItem('tukangndeso_token', token); updateSlotDisplay(); show('authResult', 'Switched ke token Tukang.'); });

  var loadCategories = function () { request('/v1/categories').then(function (body) { $('categories').innerHTML = body.data.map(function (item, index) { return '<button class="chip ' + (index === 0 ? 'selected' : '') + '" data-code="' + escapeHtml(item.code) + '">' + escapeHtml(item.name) + '</button>'; }).join(''); $('categories').querySelectorAll('[data-code]').forEach(function (button) { button.addEventListener('click', function () { $('categories').querySelectorAll('.chip').forEach(function (item) { item.classList.remove('selected'); }); button.classList.add('selected'); loadServices(button.dataset.code); }); }); loadServices(body.data[0].code); }).catch(function (error) { show('catalogResult', error.message, true); }); };
  var loadServices = function (code) { request('/v1/categories/' + encodeURIComponent(code) + '/services').then(function (body) { $('services').innerHTML = body.data.map(function (item) { return '<div class="list-item"><span><strong>' + escapeHtml(item.name) + '</strong><small>' + escapeHtml(item.id) + '</small></span><span class="price">Rp' + item.base_hourly_rate.toLocaleString('id-ID') + '/jam</span></div>'; }).join(''); }).catch(function (error) { show('catalogResult', error.message, true); }); };
  loadCategories();

  $('estimate').addEventListener('click', function () { var dateValue = $('scheduledAt').value ? new Date($('scheduledAt').value).toISOString() : null; request('/v1/pricing/estimate', { method:'POST', body:JSON.stringify({ service_id:$('serviceId').value, pricing_scheme:$('scheme').value, duration:Number($('duration').value), customer_location:{ lat:-7.4722, lng:112.4336 }, scheduled_at:dateValue, floor_level:Number($('floor').value), is_urgent:$('urgent').checked }) }).then(function (body) { show('pricingResult', body.data); }).catch(function (error) { show('pricingResult', error.message, true); }); });
  $('loadProfile').addEventListener('click', function () { request('/v1/me').then(function (body) { show('profileData', body.data); }).catch(function (error) { show('profileData', error.message, true); }); });
  $('addAddress').addEventListener('click', function () { request('/v1/me/addresses', { method:'POST', body:JSON.stringify({ label:$('addressLabel').value, full_address:$('addressFull').value, lat:Number($('addressLat').value), lng:Number($('addressLng').value), district:$('addressDistrict').value, city:$('addressCity').value, is_default:$('addressDefault').checked }) }).then(function (body) { show('addressResult', body.data); loadAddresses(); }).catch(function (error) { show('addressResult', error.message, true); }); });
  var loadAddresses = function () { request('/v1/me/addresses').then(function (body) { $('addressList').innerHTML = body.data.length ? body.data.map(function (item) { return '<div class="list-item"><span><strong>' + escapeHtml(item.label) + (item.is_default ? ' · utama' : '') + '</strong><small>' + escapeHtml(item.full_address) + ' · ' + escapeHtml(item.district) + '</small></span><button class="btn danger" data-delete="' + escapeHtml(item.id) + '">Hapus</button></div>'; }).join('') : '<p>Belum ada alamat.</p>'; $('addressList').querySelectorAll('[data-delete]').forEach(function (button) { button.addEventListener('click', function () { request('/v1/me/addresses/' + button.dataset.delete, { method:'DELETE' }).then(loadAddresses).catch(function (error) { show('addressResult', error.message, true); }); }); }); }).catch(function (error) { show('addressList', error.message, true); }); };
  $('loadAddresses').addEventListener('click', loadAddresses);

  var renderOrder = function (order, workerMode) {
    var actions = '';
    var actionMap = { PENDING:'accept', ACCEPTED:'enroute', EN_ROUTE:'arrive', ARRIVED:'start', IN_PROGRESS:'complete' };
    var action = actionMap[order.status];
    if (workerMode && action) actions = '<button class="btn" data-order-action="' + action + '" data-order-id="' + escapeHtml(order.id) + '">' + action.charAt(0).toUpperCase() + action.slice(1) + '</button>';
    return '<div class="list-item"><span><strong>' + escapeHtml(order.order_number) + ' · ' + escapeHtml(order.status) + '</strong><small>' + escapeHtml(order.service_id) + ' · Rp' + Number(order.pricing.total_estimate).toLocaleString('id-ID') + '</small></span><span>' + actions + '</span></div>';
  };
  var bindOrderActions = function () {
    document.querySelectorAll('[data-order-action]').forEach(function (button) { button.addEventListener('click', function () { var action = button.dataset.orderAction; var orderId = button.dataset.orderId; request('/v1/worker/orders/' + orderId + '/' + action, { method:'POST' }).then(function (body) { show('orderActionResult', body.data); loadIncoming(); loadActive(); }).catch(function (error) { show('orderActionResult', error.message, true); }); }); });
  };
  var loadMyOrders = function () { request('/v1/orders').then(function (body) { $('myOrdersList').innerHTML = body.data.length ? body.data.map(function (order) { return renderOrder(order, false); }).join('') : '<p>Belum ada order.</p>'; }).catch(function (error) { show('orderCreateResult', error.message, true); }); };
  var loadIncoming = function () { request('/v1/worker/orders/incoming').then(function (body) { $('incomingList').innerHTML = body.data.length ? body.data.map(function (order) { return renderOrder(order, true); }).join('') : '<p>Belum ada order masuk.</p>'; bindOrderActions(); }).catch(function (error) { show('orderActionResult', error.message, true); }); };
  var loadActive = function () { request('/v1/worker/orders/active').then(function (body) { $('activeList').innerHTML = body.data.length ? body.data.map(function (order) { return renderOrder(order, true); }).join('') : '<p>Belum ada order aktif.</p>'; bindOrderActions(); }).catch(function (error) { show('orderActionResult', error.message, true); }); };
  $('createOrder').addEventListener('click', function () { var distance = Number($('orderDistance').value); var duration = Number($('orderDuration').value); var scheme = $('orderScheme').value; var baseRate = scheme === 'hourly' ? Math.max(duration, 2) * 30000 : duration * 150000; request('/v1/orders', { method:'POST', body:JSON.stringify({ service_id:$('orderServiceId').value, pricing_scheme:scheme, estimated_duration:duration, description:$('orderDescription').value, photos:[], address_id:$('orderAddressId').value, customer_location:{ lat:-7.4722, lng:112.4336 }, scheduled_at:null, pricing:{ base_rate:baseRate, distance_km:distance, travel_cost:Math.min(Math.max(Math.round(distance * 1000), 5000), 50000), surcharge:{ holiday:0, night:0, weekend:0, urgent:0, floor:0 }, total_estimate:baseRate + Math.min(Math.max(Math.round(distance * 1000), 5000), 50000) } }) }).then(function (body) { show('orderCreateResult', body.data); $('qrisOrderId').value = body.data.id; loadMyOrders(); }).catch(function (error) { show('orderCreateResult', error.message, true); }); });
  $('loadMyOrders').addEventListener('click', loadMyOrders);
  $('loadIncoming').addEventListener('click', loadIncoming);
  $('loadActive').addEventListener('click', loadActive);

  $('generateQris').addEventListener('click', function () { request('/v1/payments/qris/create', { method:'POST', body:JSON.stringify({ order_id:$('qrisOrderId').value }) }).then(function (body) { show('qrisResult', body.data); $('paymentStatusId').value = body.data.payment_id; $('simulatePaymentId').value = body.data.payment_id; $('webhookPaymentId').value = body.data.payment_id; }).catch(function (error) { show('qrisResult', error.message, true); }); });
  $('checkPaymentStatus').addEventListener('click', function () { request('/v1/payments/' + $('paymentStatusId').value + '/status').then(function (body) { show('paymentStatusResult', body.data); }).catch(function (error) { show('paymentStatusResult', error.message, true); }); });
  $('simulatePaid').addEventListener('click', function () { request('/v1/payments/simulate-paid', { method:'POST', body:JSON.stringify({ payment_id:$('simulatePaymentId').value }) }).then(function (body) { show('simulateResult', body.data); }).catch(function (error) { show('simulateResult', error.message, true); }); });
  $('fireWebhook').addEventListener('click', function () { fetch('/v1/payments/webhook/qris', { method:'POST', headers:{ 'Content-Type':'application/json' }, body:JSON.stringify({ payment_id:$('webhookPaymentId').value, status:'paid', reference:$('webhookReference').value }) }).then(json).then(function (body) { show('webhookResult', body.data); }).catch(function (error) { show('webhookResult', error.message, true); }); });

  $('submitReview').addEventListener('click', function () { request('/v1/orders/' + $('reviewOrderId').value + '/review', { method:'POST', body:JSON.stringify({ rating:Number($('reviewRating').value), comment:$('reviewComment').value || null, photos:[] }) }).then(function (body) { show('reviewResult', body.data); }).catch(function (error) { show('reviewResult', error.message, true); }); });
  $('loadReview').addEventListener('click', function () { request('/v1/orders/' + $('reviewOrderId').value + '/review').then(function (body) { show('reviewResult', body.data); }).catch(function (error) { show('reviewResult', error.message, true); }); });
  $('loadWorkerReviews').addEventListener('click', function () { request('/v1/workers/' + $('workerReviewsId').value + '/reviews').then(function (body) { show('workerReviewsResult', body.data); }).catch(function (error) { show('workerReviewsResult', error.message, true); }); });

  $('registerWorker').addEventListener('click', function () { var skills = $('workerSkills').value.split(',').map(function (item) { return item.trim(); }).filter(Boolean); request('/v1/worker/register', { method:'POST', body:JSON.stringify({ ktp_number:$('workerKtp').value, ktp_photo_url:$('workerKtpUrl').value, bio:$('workerBio').value || null, work_radius_km:Number($('workerRadius').value), home_location:{ lat:Number($('workerLat').value), lng:Number($('workerLng').value) }, skills:skills }) }).then(function (body) { show('workerProfileResult', body.data); $('verifyWorkerId').value = body.data.user_id; }).catch(function (error) { show('workerProfileResult', error.message, true); }); });
  $('loadWorkerProfile').addEventListener('click', function () { request('/v1/worker/profile').then(function (body) { show('workerProfileResult', body.data); $('verifyWorkerId').value = body.data.user_id; }).catch(function (error) { show('workerProfileResult', error.message, true); }); });
  $('verifyWorker').addEventListener('click', function () { request('/v1/worker/' + $('verifyWorkerId').value + '/verify', { method:'POST' }).then(function (body) { show('availabilityResult', body.data); }).catch(function (error) { show('availabilityResult', error.message, true); }); });
  $('goOnline').addEventListener('click', function () { request('/v1/worker/availability', { method:'POST', body:JSON.stringify({ is_available:true }) }).then(function (body) { show('availabilityResult', body.data); }).catch(function (error) { show('availabilityResult', error.message, true); }); });
  $('goOffline').addEventListener('click', function () { request('/v1/worker/availability', { method:'POST', body:JSON.stringify({ is_available:false }) }).then(function (body) { show('availabilityResult', body.data); }).catch(function (error) { show('availabilityResult', error.message, true); }); });
  $('loadWallet').addEventListener('click', function () { request('/v1/worker/wallet').then(function (body) { show('walletData', body.data); }).catch(function (error) { show('walletData', error.message, true); }); });
  $('submitWithdraw').addEventListener('click', function () { request('/v1/worker/wallet/withdraw', { method:'POST', body:JSON.stringify({ amount:Number($('withdrawAmount').value), bank_name:$('withdrawBank').value, bank_account:$('withdrawAccount').value }) }).then(function (body) { show('withdrawResult', body.data); }).catch(function (error) { show('withdrawResult', error.message, true); }); });

  $('findCandidates').addEventListener('click', function () { request('/v1/matching/find', { method:'POST', body:JSON.stringify({ order_id:$('matchOrderId').value }) }).then(function (body) { show('matchingResult', body.data); }).catch(function (error) { show('matchingResult', error.message, true); }); });
  $('assignBest').addEventListener('click', function () { request('/v1/matching/assign', { method:'POST', body:JSON.stringify({ order_id:$('matchOrderId').value }) }).then(function (body) { show('matchingResult', body.data); }).catch(function (error) { show('matchingResult', error.message, true); }); });
  $('assignSpecific').addEventListener('click', function () { request('/v1/matching/assign', { method:'POST', body:JSON.stringify({ order_id:$('assignOrderId').value, worker_id:$('assignWorkerId').value }) }).then(function (body) { show('assignResult', body.data); }).catch(function (error) { show('assignResult', error.message, true); }); });

  $('loadReport').addEventListener('click', function () { request('/v1/admin/reports/summary').then(function (body) { show('reportResult', body.data); }).catch(function (error) { show('reportResult', error.message, true); }); });
  $('loadPendingWorkers').addEventListener('click', function () { request('/v1/admin/workers/pending').then(function (body) { if (!body.data.length) { $('pendingWorkersList').innerHTML = '<p class="hint">Tidak ada tukang pending.</p>'; show('pendingWorkersResult', 'Kosong.'); return; } $('pendingWorkersList').innerHTML = body.data.map(function (w) { return '<div class="list-item"><span><strong>' + escapeHtml(w.user_id.slice(0, 12)) + '…</strong><small>Skills: ' + escapeHtml(w.skills.join(', ')) + '</small></span><button class="btn primary" data-verify="' + escapeHtml(w.user_id) + '">Verify</button></div>'; }).join(''); $('pendingWorkersList').querySelectorAll('[data-verify]').forEach(function (btn) { btn.addEventListener('click', function () { $('adminWorkerId').value = btn.dataset.verify; request('/v1/admin/workers/' + btn.dataset.verify + '/verify', { method:'POST' }).then(function (r) { show('pendingWorkersResult', r.data); }).catch(function (e) { show('pendingWorkersResult', e.message, true); }); }); }); }).catch(function (error) { show('pendingWorkersResult', error.message, true); }); });
  $('adminVerify').addEventListener('click', function () { request('/v1/admin/workers/' + $('adminWorkerId').value + '/verify', { method:'POST' }).then(function (body) { show('adminWorkerResult', body.data); }).catch(function (error) { show('adminWorkerResult', error.message, true); }); });
  $('adminSuspend').addEventListener('click', function () { request('/v1/admin/workers/' + $('adminWorkerId').value + '/suspend', { method:'POST' }).then(function (body) { show('adminWorkerResult', body.data); }).catch(function (error) { show('adminWorkerResult', error.message, true); }); });
  $('adminReactivate').addEventListener('click', function () { request('/v1/admin/workers/' + $('adminWorkerId').value + '/reactivate', { method:'POST' }).then(function (body) { show('adminWorkerResult', body.data); }).catch(function (error) { show('adminWorkerResult', error.message, true); }); });
  $('forceTransition').addEventListener('click', function () { request('/v1/admin/orders/' + $('forceOrderId').value + '/force-transition', { method:'POST', body:JSON.stringify({ to_status:$('forceTargetStatus').value, note:$('forceNote').value || null }) }).then(function (body) { show('forceResult', body.data); }).catch(function (error) { show('forceResult', error.message, true); }); });

  $('seedDemo').addEventListener('click', function () { fetch('/dev/seed/demo', { method:'POST' }).then(json).then(function (body) { var lines = ['=== SEED BERHASIL ===\\n']; lines.push('CUSTOMERS:'); body.data.customers.forEach(function (c) { lines.push('  ' + c.phone + ' (' + c.name + ')'); lines.push('    ' + c.token); }); lines.push('\\nWORKERS:'); body.data.workers.forEach(function (w) { lines.push('  ' + w.phone + ' (' + w.name + ') skills=' + w.skills.join(',')); lines.push('    ' + w.token); }); lines.push('\\nADMIN:'); lines.push('  ' + body.data.admin.phone + ' (' + body.data.admin.name + ')'); lines.push('    ' + body.data.admin.token); show('seedResult', lines.join('\\n')); }).catch(function (error) { show('seedResult', error.message, true); }); });
}());
</script>
</body>
</html>`;
